name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ beta-1.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
       name: Build
       run: |
          docker build -t getcarrier/perfgun:beta-1.0-3.7 -f docker/Dockerfile_3_7 .
          docker build -t getcarrier/perfgun:beta-1.0-3.6 -f docker/Dockerfile_3_6 .
          docker build -t getcarrier/perfgun:beta-1.0-3.1 -f docker/Dockerfile_3_1 .
    -
       name: Push
       run: |
         docker push getcarrier/perfgun:beta-1.0-3.7
         docker push getcarrier/perfgun:beta-1.0-3.6
         docker push getcarrier/perfgun:beta-1.0-3.1